/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: (typeof import('element-plus/es'))['ElAside']
    ElAvatar: (typeof import('element-plus/es'))['ElAvatar']
    ElBreadcrumb: (typeof import('element-plus/es'))['ElBreadcrumb']
    ElBreadcrumbItem: (typeof import('element-plus/es'))['ElBreadcrumbItem']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox']
    ElCol: (typeof import('element-plus/es'))['ElCol']
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider']
    ElContainer: (typeof import('element-plus/es'))['ElContainer']
    ElDatePicker: (typeof import('element-plus/es'))['ElDatePicker']
    ElDialog: (typeof import('element-plus/es'))['ElDialog']
    ElDivider: (typeof import('element-plus/es'))['ElDivider']
    ElDropdown: (typeof import('element-plus/es'))['ElDropdown']
    ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem']
    ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu']
    ElForm: (typeof import('element-plus/es'))['ElForm']
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
    ElHeader: (typeof import('element-plus/es'))['ElHeader']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElMain: (typeof import('element-plus/es'))['ElMain']
    ElMenu: (typeof import('element-plus/es'))['ElMenu']
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem']
    ElOption: (typeof import('element-plus/es'))['ElOption']
    ElPagination: (typeof import('element-plus/es'))['ElPagination']
    ElResult: (typeof import('element-plus/es'))['ElResult']
    ElRow: (typeof import('element-plus/es'))['ElRow']
    ElSelect: (typeof import('element-plus/es'))['ElSelect']
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
    ElTable: (typeof import('element-plus/es'))['ElTable']
    ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn']
    ElTabPane: (typeof import('element-plus/es'))['ElTabPane']
    ElTabs: (typeof import('element-plus/es'))['ElTabs']
    ElTag: (typeof import('element-plus/es'))['ElTag']
    HeaderCrumb: (typeof import('./../components/MainHeader/c-cpns/header-crumb.vue'))['default']
    HeaderInfo: (typeof import('./../components/MainHeader/c-cpns/header-info.vue'))['default']
    IEpChromeFilled: (typeof import('~icons/ep/chrome-filled'))['default']
    IEpEdit: (typeof import('~icons/ep/edit'))['default']
    IEpElementPlus: (typeof import('~icons/ep/element-plus'))['default']
    MainHeader: (typeof import('./../components/MainHeader/index.vue'))['default']
    MainMenu: (typeof import('./../components/MainMenu/index.vue'))['default']
    QrCode: (typeof import('./../components/QrCode/index.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
}
